version: "3.3"
services:
    web:
        image: nginx:latest
        container_name: web
        restart: always
        ports:
          - ${APP_IP}:${APP_PORT}:${CONTAINER_PORT}
        volumes:
          - ${APP_PATH_HOST}:${CONTAINER_PATH_HOST}
          - ${APP_PATH_NGINX_CONFIG}:/etc/nginx/conf.d
          - ${APP_PATH_NGINX_LOG}:/var/log/nginx/
        working_dir: ${CONTAINER_PATH_HOST}
        depends_on:
          - php
        links:
          - php
          - mysql
          - node

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
          - ${DB_PATH_HOST}:/var/lib/mysql

    php:
        build: ./php
        container_name: php-fpm
        volumes:
          - ${APP_PATH_HOST}:${CONTAINER_PATH_HOST}
        working_dir: ${CONTAINER_PATH_HOST}

    node:
        image: node:latest
        volumes:
          - ${APP_PATH_HOST}:${CONTAINER_PATH_HOST}
        working_dir: ${CONTAINER_PATH_HOST}
        tty: true

    rabbitmq:
        image: rabbitmq:latest
        container_name: rabbitmq
  

